export const APP_CONFIG = {
  DEBUG_MODE: true,
  USE_MOCK_HAND_TRACKING: false,
  CAMERA_FRAME_INTERVAL_MS: 120,
  VISIONKIT_FPS: 30,
  COPY_ANIMATION_MS: 620,
  MIN_FRAME_SIZE: 0.12,
  WORK_CANVAS_MAX_EDGE: 720,
} as const;
